export const LOAD_FILTER_TEMPLATES_BY_CATALOG_SLUG =
  "LOAD_FILTER_TEMPLATES_BY_CATALOG_SLUG";
export const CREATE_FILTER_TEMPLATE = "CREATE_FILTER_TEMPLATE";
export const UPDATE_FILTER_TEMPLATE = "UPDATE_FILTER_TEMPLATE";
export const DELETE_FILTER_TEMPLATE = "DELETE_FILTER_TEMPLATE";
