export const LOAD_USER_SETTINGS = "LOAD_USER_SETTINGS";
export const CREATE_USER_SETTING = "CREATE_USER_SETTING";
export const UPDATE_USER_SETTING = "UPDATE_USER_SETTING";
export const DELETE_USER_SETTING = "DELETE_USER_SETTING";
