<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260211110812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE filter_templates (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filter_name VARCHAR(255) NOT NULL, catalog_slug VARCHAR(255) NOT NULL, catalog_name VARCHAR(255) DEFAULT NULL, public BOOLEAN NOT NULL, filter_content JSONB NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, author_id INT DEFAULT NULL, editor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B9C3B163F675F31B ON filter_templates (author_id)');
        $this->addSql('CREATE INDEX IDX_B9C3B1636995AC4C ON filter_templates (editor_id)');
        $this->addSql('COMMENT ON COLUMN filter_templates.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN filter_templates.filter_name IS \'Наименование фильтра в интерфейсе\'');
        $this->addSql('COMMENT ON COLUMN filter_templates.catalog_slug IS \'Идентификатор справочника\'');
        $this->addSql('COMMENT ON COLUMN filter_templates.catalog_name IS \'Наименование справочника\'');
        $this->addSql('COMMENT ON COLUMN filter_templates.public IS \'Виден ли фильтр другим пользователям\'');
        $this->addSql('COMMENT ON COLUMN filter_templates.filter_content IS \'Функциональное содержание фильтра\'');
        $this->addSql('COMMENT ON COLUMN filter_templates.created_at IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN filter_templates.updated_at IS \'Дата обновления\'');
        $this->addSql('COMMENT ON COLUMN filter_templates.author_id IS \'Пользователь, создавший запись\'');
        $this->addSql('COMMENT ON COLUMN filter_templates.editor_id IS \'Пользователь, обновивший запись\'');
        $this->addSql('CREATE TABLE user_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) DEFAULT NULL, entity_name JSONB NOT NULL, type JSONB NOT NULL, username VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_36D54C77A76ED395 ON user_events (user_id)');
        $this->addSql('COMMENT ON COLUMN user_events.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN user_events.description IS \'Описание\'');
        $this->addSql('COMMENT ON COLUMN user_events.entity_name IS \'Объект\'');
        $this->addSql('COMMENT ON COLUMN user_events.type IS \'Тип события\'');
        $this->addSql('COMMENT ON COLUMN user_events.username IS \'Имя пользователя\'');
        $this->addSql('COMMENT ON COLUMN user_events.created_at IS \'Дата создания\'');
        $this->addSql('COMMENT ON COLUMN user_events.user_id IS \'Пользователь\'');
        $this->addSql('CREATE TABLE user_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C844C5A76ED395 ON user_settings (user_id)');
        $this->addSql('COMMENT ON COLUMN user_settings.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN user_settings.name IS \'Наименование\'');
        $this->addSql('COMMENT ON COLUMN user_settings.value IS \'Значение\'');
        $this->addSql('COMMENT ON COLUMN user_settings.description IS \'Описание\'');
        $this->addSql('COMMENT ON COLUMN user_settings.user_id IS \'Пользователь\'');
        $this->addSql('CREATE TABLE user_tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B29A9ECFA76ED395 ON user_tasks (user_id)');
        $this->addSql('COMMENT ON COLUMN user_tasks.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN user_tasks.name IS \'Наименование\'');
        $this->addSql('COMMENT ON COLUMN user_tasks.type IS \'Тип\'');
        $this->addSql('COMMENT ON COLUMN user_tasks.started_at IS \'ДатаВремя начала\'');
        $this->addSql('COMMENT ON COLUMN user_tasks.finished_at IS \'ДатаВремя окончания\'');
        $this->addSql('COMMENT ON COLUMN user_tasks.filename IS \'Наименование файла\'');
        $this->addSql('COMMENT ON COLUMN user_tasks.status IS \'Статус\'');
        $this->addSql('COMMENT ON COLUMN user_tasks.user_id IS \'Пользователь\'');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, login_lc VARCHAR(255) NOT NULL, login VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, patronymic VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, roles TEXT NOT NULL, token VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, employment_date DATE DEFAULT NULL, dismissal_date DATE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON COLUMN users.id IS \'Идентификатор\'');
        $this->addSql('COMMENT ON COLUMN users.login_lc IS \'Уникальный логин\'');
        $this->addSql('COMMENT ON COLUMN users.login IS \'Логин\'');
        $this->addSql('COMMENT ON COLUMN users.last_name IS \'Фамилия\'');
        $this->addSql('COMMENT ON COLUMN users.first_name IS \'Имя\'');
        $this->addSql('COMMENT ON COLUMN users.patronymic IS \'Отчество\'');
        $this->addSql('COMMENT ON COLUMN users.password IS \'Хешированный пароль\'');
        $this->addSql('COMMENT ON COLUMN users.roles IS \'Роли\'');
        $this->addSql('COMMENT ON COLUMN users.token IS \'Токен\'');
        $this->addSql('COMMENT ON COLUMN users.email IS \'Почта\'');
        $this->addSql('COMMENT ON COLUMN users.employment_date IS \'Дата приема\'');
        $this->addSql('COMMENT ON COLUMN users.dismissal_date IS \'Дата увольнения\'');
        $this->addSql('ALTER TABLE filter_templates ADD CONSTRAINT FK_B9C3B163F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE filter_templates ADD CONSTRAINT FK_B9C3B1636995AC4C FOREIGN KEY (editor_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_events ADD CONSTRAINT FK_36D54C77A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_settings ADD CONSTRAINT FK_5C844C5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_tasks ADD CONSTRAINT FK_B29A9ECFA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE filter_templates DROP CONSTRAINT FK_B9C3B163F675F31B');
        $this->addSql('ALTER TABLE filter_templates DROP CONSTRAINT FK_B9C3B1636995AC4C');
        $this->addSql('ALTER TABLE user_events DROP CONSTRAINT FK_36D54C77A76ED395');
        $this->addSql('ALTER TABLE user_settings DROP CONSTRAINT FK_5C844C5A76ED395');
        $this->addSql('ALTER TABLE user_tasks DROP CONSTRAINT FK_B29A9ECFA76ED395');
        $this->addSql('DROP TABLE filter_templates');
        $this->addSql('DROP TABLE user_events');
        $this->addSql('DROP TABLE user_settings');
        $this->addSql('DROP TABLE user_tasks');
        $this->addSql('DROP TABLE users');
    }
}
