export const GET_DECRYPTIONS = "GET_DECRYPTIONS";
export const GET_DECRYPTION = "GET_DECRYPTION";
export const UPDATE_DECRYPTION = "UPDATE_DECRYPTION";
export const SET_DECRYPTION_ID = "SET_DECRYPTION_ID";
export const STATION_ID = "STATION_ID";
export const DECRYPTING_RESULT = "DECRYPTING_RESULT";
